server:
  address: ${SERVER_ADDRESS:localhost}
  port: ${SERVER_PORT:8080}
spring:
  application:
    name: mesh-short
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    platform: mysql
    url: jdbc:mysql://${MYSQL_SERVICE_HOST:localhost}:${MYSQL_SERVICE_PORT:3306}/${MYSQL_SERVICE_DB_NAME:db_shorturl}?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: ${MYSQL_SERVICE_USER:root}
    password: ${MYSQL_SERVICE_PASSWORD:123456}
    #The HikariCP pooled DataSource.
    hikari:
      pool-name: Retail_HikariCP
      minimum-idle: 5 #min connection number
      idle-timeout: 180000 #Idle connection survival time, default: 600000ms
      maximum-pool-size: 10 #Maximum number of connections in the connection pool, default: 10
      auto-commit: true  #auto-commit, default: true
      max-lifetime: 1800000 #Controls the longest lifetime of connections in the pool. A value of 0 indicates an infinite lifetime，, default: 1800000ms
      connection-timeout: 6000 #6000 #mysql connection timeout, default: 30000ms
      connection-test-query: SELECT 1
  jpa:
    show-sql: ${DEBUG_MODEL:true}
    properties:
      hibernate:
        format_sql: ${DEBUG_MODEL:true}
        max_fetch_depth: 1
        ddl-auto: update
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        open-in-view: false
  redis:
    database: 0
    host: ${REDIS_SERVICE_HOST:localhost}
    port: ${REDIS_SERVICE_PORT:6379}
    password: ${REDIS_SERVICE_PASSWORD:}
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
  # config thymeleaf
  thymeleaf:
    mode: HTML
    encoding: UTF-8
    #Develop configuration: false
    cache: false
    #Templates configuration
    prefix: classpath:/templates

redis.address: redis://${spring.redis.host}:${spring.redis.port}

cn.willlu.host: ${SERVER_HTTP:http}://${server.address}:${server.port}
cn.willlu.host.url: ${cn.willlu.host}/short/