server:
  port: 8080
spring:
  application:
    name: mesh-short
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    platform: mysql
    url: jdbc:mysql://localhost:3306/db_shorturl?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  jpa:
    show-sql: true
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
  # config thymeleaf
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    #Develop configuration: false
    cache: false
    #Templates configuration
    prefix: classpath:/templates

redis.address: redis://${spring.redis.host}:${spring.redis.port}

cn.willlu.host: http://192.168.2.100:8080
cn.willlu.host.url: ${cn.willlu.host}/short/

thread.pool.corePoolSize: 32
thread.pool.delay: 2